version: '3.1'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: protagoniza-pretx:latest
    container_name: protagoniza-pretx
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - mongo-express

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: protagoniza
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/